### ISSUE TITLE
greenkeeper-lockfile-update fails with git merge error

### ISSUE THREAD

**Issue by LewisTehMinerz** [greenkeeperio/greenkeeper-lockfile#216]
[CI](https://circleci.com/gh/DiscordExchange/discordexchange.js/105)
[Greenkeeper issue on my repo](https://github.com/DiscordExchange/discordexchange.js/issues/13)

Got this error where greenkeeper-lockfile-update fails with a git merge error relating to package-lock.json.
This could perfectly be caused by the fact that we pull out an older copy of package-lock.json earlier when we restore the cache, but I've never seen this issue occur before.

[For example, this worked perfectly fine with the current CI setup.](https://github.com/DiscordExchange/discordexchange.js/pull/12)

I have no clue how to fix this.

**Comment by janl** [comment]
@LewisTehMinerz sorry for the trouble here. Just checking, because there might be an easy way out: if you have only public dependencies (npm registry or git), you don’t need `greenkeeper-lockfile` anymore.

If you have private dependencies, you’ll need it for now, and we can look into debugging your problem, just let us know here.

**Comment by LewisTehMinerz** [comment]
@janl So we don't actually need to run greenkeeper-lockfile?

**Comment by LewisTehMinerz** [comment]
we've removed greenkeeper-lockfile from our CI stage, we'll see what happens

**Comment by LewisTehMinerz** [comment]
everything works.
