### ISSUE TITLE
Be smarter about when to upload the shrinkwrap

### ISSUE THREAD

**Issue by boennemann** [greenkeeperio/greenkeeper-lockfile#6]
Right now this plugin uploads the updated shrinkwrap whenever it can.
In cases where the Greenkeeper update is an in-range update and the build passes this wouldn't be necessary anymore.
Furthermore as the branch is then modified Greenkeeper won't delete it anymore.

By figuring out whether the current update is in-range, or out of range, and looking at the result, we could avoid this.

**Comment by sanderploegsma** [comment]
My situation is slightly different: greenkeeper does delete the branch, but the extra commit triggers another build, which then errors because the branch is missing. This creates a flood of build failures in our feeds, which is highly annoying.

I agree with @boennemann, in-range updates should not update shrinkwrap files.

**Comment by boennemann** [comment]
Should be addressed by this https://github.com/greenkeeperio/greenkeeper/commit/68260b19ca780f36997b4ce722a9e526da233a70
